version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: npm run test
          command: npm run test -- --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

workflows:
  integration_tests:
    jobs:
      - test
