version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm install -g firebase-tools
          command: npm install -g firebase-tools
      - run:
          name: Enable extension dev
          command: firebase --open-sesame extdev
      - save_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - restore_cache:
          key: dependency-cache-v1-functions-{{ checksum "functions/package-lock.json" }}
      - run:
          name: npm install inside functions
          command: cd functions && npm install
      - save_cache:
          key: dependency-cache-v1-functions-{{ checksum "functions/package-lock.json" }}
          paths:
            - ./functions/node_modules
      - run:
          name: npm run test:ci
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

workflows:
  integration_tests:
    jobs:
      - test
